---
title: "PGS Foglizzese - TSEC"
output:
  pagedown::poster_jacobs:
    css:
    - poster-jacobs.css
    self_contained: false
    pandoc_args: --mathjax
---

```{r include=FALSE}
library(datavolley)
suppressPackageStartupMessages(library(tidyverse))
library(gt)
library(gtExtras)

knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      error = FALSE,
                      message = FALSE)

source("utils.R")
noi <- "BraslovÄe"
loro <- teams(x)[teams(x) != noi]

```




S1
================================================================================

```{r risultato}
x <- dv_read("example.dvw")

x$meta$teams %>%
    select(team, sets_won) %>% 
    gt(id = "one") %>%
    tab_header(title = "Risultato finale") %>% 
    fmt_markdown(columns = everything()) %>%
    tab_options(table.width = px(90),
                column_labels.hidden = TRUE) %>% 
    opt_css(
    css = "
    #one .gt_header {
      padding: 2px 3px;
      font-size: 7px;
      color: lightgreen;
    }
    #one .gt_row {
      padding: 2px 3px;
      font-size: 7px;
    }
    #one .gt_col_heading {
      text-align: center !important;
    }
    ")

```


S2
================================================================================

```{r meta1}
data <- as.character(x$meta$match$date)
stag <- x$meta$match$season
lea <- x$meta$match$league
pha <- x$meta$match$phase
num <- x$meta$match$match_number

meta1 <- tibble(name = c("Data", "Stagione", "Campionato", "Fase", "Partita"),
                values = c(data, stag, lea, pha, num))


meta1 %>% 
    gt(id = "two") %>%
    tab_options(#table.width = px(150),
                column_labels.hidden = TRUE) %>% 
    tab_options(table.width = px(200)) %>% 
    opt_css(
    css = "
    #two .gt_header {
      padding: 2px 3px;
      font-size: 7;
      color: lightgreen;
    }
    #two .gt_row {
      padding: 2px 3px;
      font-size: 7px;
    }
    #two .gt_col_heading {
      text-align: center !important;
    }
    ")

```



S3
================================================================================

```{r meta3}
x$meta$result %>%
    mutate(Set = row_number()) %>% 
    unite("Parziali", score_intermediate1:score_intermediate3, sep = " / ") %>% 
    select(Set, Durata = duration, Parziali, Punteggio = score) %>% 
    gt(id = "third") %>%
    cols_align(
    align = "center") %>% 
    tab_options(table.width = px(200)) %>% 
    opt_css(
    css = "
    #third .gt_col_heading {
      padding: 2px 3px;
      font-size: 10px;
    }
    #third .gt_row {
      padding: 2px 3px;
      font-size: 7px;
    }
    #third .gt_col_heading {
      text-align: center !important;
    }
    ")

```


S4
================================================================================
```{r main}
noi <- home_team(x)

t1 <- x$meta$players_h %>% 
    select(number, name, starting_position_set1:starting_position_set5) %>% 
    select(where(~sum(!is.na(.x)) > 0)) %>% 
    rename_with(~str_remove(.x, "starting_position_"))

##################
# Functions
# Points
vr_points <- function(x, by = "player", team_select = noi) {
    as_for_datavolley <- TRUE
    by <- match.arg(tolower(by), c("player", "set"))
    if (by == "player") {
        vr_pts <- plays(x) %>% 
            dplyr::filter(.data$team %in% team_select, .data$player_id != "unknown player") %>% 
            group_by(.data$player_id) %>%
            dplyr::summarize(Tot = sum(.data$evaluation_code == "#" & .data$skill %in% c("Serve", "Attack", "Block")),
                             # BP = sum(.data$evaluation_code == "#" & .data$skill %in% c("Serve", "Attack", "Block") & .data$serving_team == team_select),
                             Nerr = sum((.data$evaluation %eq% "Error" & .data$skill %in% c("Serve", "Reception", "Attack", if (!as_for_datavolley) "Set", if (!as_for_datavolley) "Freeball")) | (!as_for_datavolley & .data$evaluation %eq% "Invasion" & .data$skill %eq% "Block") | (.data$evaluation %eq% "Blocked" & .data$skill %eq% "Attack")),
                             'W-L' = .data$Tot - .data$Nerr)
        vr_pts <- vr_pts %>%
            bind_rows(
                plays(x) %>% dplyr::filter(.data$team %in% team_select, .data$player_id != "unknown player") %>%
                mutate(player_id = "Team total") %>% 
                group_by(.data$player_id) %>%
                dplyr::summarize(Tot = sum(.data$evaluation_code == "#" & .data$skill %in% c("Serve", "Attack", "Block")),
                                 # BP = sum(.data$evaluation_code == "#" & .data$skill %in% c("Serve", "Attack", "Block") & .data$serving_team == team_select),
                                 Nerr = sum((.data$evaluation %eq% "Error" & .data$skill %in% c("Serve", "Reception", "Attack", if (!as_for_datavolley) "Set", if (!as_for_datavolley) "Freeball")) | (!as_for_datavolley & .data$evaluation %eq% "Invasion" & .data$skill %eq% "Block") | (.data$evaluation %eq% "Blocked" & .data$skill %eq% "Attack")),
                                 'W-L' = .data$Tot - .data$Nerr))
    } else if (by == "set") {
        y <- plays(x)
        y$team_points <- if (team_select %eq% datavolley::home_team(y)) y$home_team_score else if (team_select %eq% datavolley::visiting_team(y)) y$visiting_team_score else NA_integer_
        vr_pts <- y %>% 
            group_by(.data$set_number) %>%
            dplyr::summarize(Ser = sum(.data$evaluation_code == "#" & .data$skill == "Serve" & .data$team %in% team_select, na.rm = TRUE),
                             Atk = sum(.data$evaluation_code == "#" & .data$skill == "Attack" & .data$team %in% team_select, na.rm = TRUE),
                             Blo = sum(.data$evaluation_code == "#" & .data$skill == "Block" & .data$team %in% team_select, na.rm = TRUE),
                             Tot = sum(.data$Ser, .data$Atk, .data$Blo),
                             "Op.Er" = max(.data$team_points, na.rm = TRUE) - .data$Ser - .data$Atk - .data$Blo)
    }
    vr_pts
}
# Serve
vr_serve <- function(x, team, by = "player", team_select = noi){
    y <- plays(x)
    if (by == "player") {
        y %>% dplyr::filter(.data$team %in% team_select, .data$player_id != "unknown player", 
                            .data$skill == "Serve") %>% 
            group_by(.data$player_id) %>%
            dplyr::summarize(Tot = n(),
                      Err = sum(.data$evaluation %eq% "Error"),
                      Pts = sum(.data$evaluation %eq% "Ace"),
                      Neg = sum(.data$evaluation %eq% "Negative, opponent free attack"),
                      Pos = sum(.data$evaluation %eq% "Positive, no attack") + 
                              sum(.data$evaluation %eq% "Positive, opponent some attack") + 
                               sum(.data$evaluation %eq% "OK, no first tempo possible")) %>%
            bind_rows(
                y %>% dplyr::filter(.data$team %in% team_select, .data$player_id != "unknown player", .data$skill == "Serve") %>% 
                    mutate(player_id = "Team total")%>% group_by(.data$player_id) %>%
                    dplyr::summarize(Tot = n(),
                              Err = sum(.data$evaluation %eq% "Error"),
                              Pts = sum(.data$evaluation %eq% "Ace"),
                              Neg = sum(.data$evaluation %eq% "Negative, opponent free attack"),
                              Pos = sum(.data$evaluation %eq% "Positive, no attack") + 
                                      sum(.data$evaluation %eq% "Positive, opponent some attack") + 
                                       sum(.data$evaluation %eq% "OK, no first tempo possible"))
            )
    } else if(by == "set") {
        y %>% dplyr::filter(.data$team %in% team_select, .data$player_id != "unknown player", 
                            .data$skill == "Serve") %>% 
            group_by(.data$set_number) %>%
            dplyr::summarize(Tot = n(),
                      Err = sum(.data$evaluation %eq% "Error"),
                      Pts = sum(.data$evaluation %eq% "Ace"),
                              Neg = sum(.data$evaluation %eq% "Negative, opponent free attack"),
                              Pos = sum(.data$evaluation %eq% "Positive, no attack") + 
                                      sum(.data$evaluation %eq% "Positive, opponent some attack") + 
                                       sum(.data$evaluation %eq% "OK, no first tempo possible"))
    }
}
# Reception
vr_reception <- function(x, team, by = "player", file_type = "indoor", team_select = noi){
    y <- plays(x)
    if (by == "player"){
        y %>% 
            dplyr::filter(.data$team %in% team_select, .data$player_id != "unknown player", 
                          .data$skill == "Reception") %>% 
            group_by(.data$player_id) %>%
            dplyr::summarize(Tot = n(),
                             Err = sum(.data$evaluation %eq% "Error"),
                             'Neg%' = paste0(round(mean(.data$evaluation_code %in% c("-", "!", "/")), 2)*100, "%"),
                             'Pos%' = paste0(round(mean(.data$evaluation_code %in% c("+", "#", "#+")), 2)*100, "%"),
                             '(Exc%)' = paste0("(", round(mean(.data$evaluation_code %in% c("#")), 2)*100, "%)")) %>%
            bind_rows(
                y %>% 
                    dplyr::filter(.data$team %in% team_select, .data$player_id != "unknown player", 
                                  .data$skill == "Reception") %>% 
                mutate(player_id = "Team total") %>%
                group_by(.data$player_id) %>%
                dplyr::summarize(Tot = n(),
                                 Err = sum(.data$evaluation %eq% "Error"),
                                 'Neg%' = paste0(round(mean(.data$evaluation_code %in% c("!", "/")), 2)*100, "%"),

                                 'Pos%' = paste0(round(mean(.data$evaluation_code %in% c("+", "#", "#+")), 2)*100, "%"),
                                 '(Exc%)' = paste0("(", round(mean(.data$evaluation_code %in% c("#")), 2)*100, "%)")))
    } else if (by == "set") {
        y %>% dplyr::filter(.data$team %in% team_select, .data$player_id != "unknown player", .data$skill == "Reception") %>% group_by(.data$set_number) %>%
            dplyr::summarize(Tot = n(),
                             Err = sum(.data$evaluation %eq% "Error"),
                             'Pos%' = paste0(round(mean(.data$evaluation_code %in% c("+", "#", "#+")), 2)*100, "%"),
                             'Neg%' = paste0(round(mean(.data$evaluation_code %in% c("!", "/")), 2)*100, "%"),

                             '(Exc%)' = paste0("(", round(mean(.data$evaluation_code %in% c("#")), 2)*100, "%)"))
    }
}
# Attack
vr_attack <- function(x, team, by = "player", team_select = noi){
    y <- plays(x)
    if (by == "player") {
        y %>% 
            dplyr::filter(.data$team %in% team_select, 
                          .data$player_id != "unknown player", 
                          .data$skill == "Attack") %>% 
            group_by(.data$player_id) %>%
            dplyr::summarize(Tot = n(),
                      Err = sum(.data$evaluation %eq% "Error"),
                      Blo = sum(.data$evaluation %eq% "Blocked"),
                      'Pts' = sum(.data$evaluation %eq% "Winning attack"),
                      'Pts%' = paste0(round(mean(.data$evaluation %eq% "Winning attack"), 2)*100, "%")) %>%
            bind_rows(
                y %>% 
                    dplyr::filter(.data$team %in% team_select, 
                                  .data$player_id != "unknown player", 
                                  .data$skill == "Attack") %>% 
                    mutate(player_id = "Team total") %>%
                    group_by(.data$player_id) %>%
                    dplyr::summarize(Tot = n(),
                              Err = sum(.data$evaluation %eq% "Error"),
                              Blo = sum(.data$evaluation %eq% "Blocked"),
                              'Pts' = sum(.data$evaluation %eq% "Winning attack"),
                              'Pts%' = paste0(round(mean(.data$evaluation %eq% "Winning attack"), 2)*100, "%")))
    } else if (by == "set") {
        y %>% 
            dplyr::filter(.data$team %in% team_select, 
                          .data$player_id != "unknown player", 
                          .data$skill == "Attack") %>% 
            group_by(.data$set_number) %>%
            dplyr::summarize(Tot = n(),
                      Err = sum(.data$evaluation %eq% "Error"),
                      Blo = sum(.data$evaluation %eq% "Blocked"),
                      'Pts' = sum(.data$evaluation %eq% "Winning attack"),
                      'Pts%' = paste0(round(mean(.data$evaluation %in% "Winning attack"), 2)*100, "%"))
    }
}
vr_freeball <- function(x, team, by = "player", team_select = noi){
    y <- plays(x)
    if (by == "player") {
        y %>% 
            dplyr::filter(.data$team %in% team_select, 
                          .data$player_id != "unknown player", 
                          .data$skill == "Freeball") %>% 
            group_by(.data$player_id) %>%
            dplyr::summarize(Tot = n(),
                      Err = sum(.data$evaluation %eq% "Error")) %>%
            bind_rows(
                y %>% 
                    dplyr::filter(.data$team %in% team_select, 
                                  .data$player_id != "unknown player", 
                                  .data$skill == "Freeball") %>% 
                    mutate(player_id = "Team total") %>%
                    group_by(.data$player_id) %>%
                    dplyr::summarize(Tot = n(),
                              Err = sum(.data$evaluation %eq% "Error")))
    } else if (by == "set") {
        y %>% 
            dplyr::filter(.data$team %in% team_select, 
                          .data$player_id != "unknown player", 
                          .data$skill == "Freeball") %>% 
            group_by(.data$set_number) %>%
            dplyr::summarize(Tot = n(),
                      Err = sum(.data$evaluation %eq% "Error"))
    }
}
# Block
vr_block <- function(x, team, by = "player", team_select = noi){
    y <- plays(x)
    if (by == "player"){
        y %>% 
            dplyr::filter(.data$team %in% team_select, 
                          .data$player_id != "unknown player") %>% 
            group_by(.data$player_id) %>%
            dplyr::summarize(Punto = sum(.data$evaluation %eq% "Winning block" & .data$skill %eq% "Block")) %>%
            bind_rows(
                y %>% 
                    dplyr::filter(.data$team %in% team_select, 
                                  .data$player_id != "unknown player") %>% 
                    mutate(player_id = "Team total") %>%
                    group_by(.data$player_id) %>%
                    dplyr::summarize(Punto = sum(.data$evaluation %eq% "Winning block" & .data$skill %eq% "Block")))
    } else if (by == "set") {
        y %>% dplyr::filter(.data$team %in% team_select, .data$player_id != "unknown player") %>% group_by(.data$set_number) %>%
            dplyr::summarize(Punto = sum(.data$evaluation %eq% "Winning block" & .data$skill %eq% "Block"))
    }
}




#####################
# POINTS
t2 <- vr_points(x, by = "set", team_select = noi)
t3 <- vr_points(x, by = "player", team_select = noi)

# SERVE
t4 <- vr_serve(x, by = "set", team_select = noi)
t5 <- vr_serve(x, by = "player", team_select = noi)

# RECEPTION
t6 <- vr_reception(x, by = "set", team_select = noi)
t7 <- vr_reception(x, by = "player", team_select = noi)

# ATTACK
t8 <- vr_attack(x, by = "set", team_select = noi)
t9 <- vr_attack(x, by = "player", team_select = noi)
t10 <- vr_freeball(x, by = "set", team_select = noi)
t11 <- vr_freeball(x, by = "player", team_select = noi)

# BLOCK
t12 <- vr_block(x, by = "set", team_select = noi)
t13 <- vr_block(x, by = "player", team_select = noi)



######################
# TABLE
y <- plays(x)
t1 %>% 
    left_join(y %>% 
                  dplyr::select(player_id, player_name) %>% 
                  filter(!is.na(player_id)) %>% 
                  distinct(), by = c("name" = "player_name")) %>% 
    left_join(t3, by = "player_id") %>% 
    left_join(t5, by = "player_id") %>%
    left_join(t7, by = "player_id") %>%
    left_join(t9, by = "player_id") %>%
    left_join(t11, by = "player_id") %>%
    left_join(t13, by = "player_id") %>%
    select(-player_id) %>% 
    mutate(across(set1:set3, ~replace_na(.x, "-"))) %>% 
    ### GT TABLE
    gt(id = "four") %>%
    tab_header(
      title = paste0(noi)) %>% 
    tab_spanner(
        label = "Punti",
        columns = Tot.x:`W-L`) %>% 
    tab_spanner(
        label = "Battuta",
        columns = Tot.y:Pos) %>% 
    tab_spanner(
        label = "Ricezione",
        columns = Tot.x.x:`(Exc%)`) %>% 
    tab_spanner(
        label = "Attacco",
        columns = Tot.y.y:`Pts%`) %>% 
    tab_spanner(
        label = "Freeball",
        columns = Tot:Err.y.y) %>%
    tab_spanner(
        label = "Muro",
        columns = Punto) %>%
    cols_label(
        Tot.x = html("<strong>Tot</strong>"),
        Nerr = html("<strong>Err</strong>"),
        `W-L` = html("D"),
        Tot.y = html("<strong>Tot</strong>"),
        Err.x = html("<strong>Err</strong>"),
        Pts.x = html("Pts"),
        Tot.x.x = html("<strong>Tot</strong>"),
        Err.y = html("<strong>Err</strong>"),
        Tot.y.y = html("<strong>Tot</strong>"),
        Err.x.x = html("<strong>Err</strong>"),
        Pts.y = html("Pts"),
        Tot = html("<strong>Tot</strong>"),
        Err.y.y = html("<strong>Err</strong>"),
        Punto = html("Pts")) %>% 
    cols_align(
    align = "center") %>% 
    tab_options(table.width = px(700)) %>% 
    opt_css(
    css = "
    #four .gt_col_heading {
      padding: 2px 3px;
      font-size: 8px;
    }
     #four .gt_column_spanner {
      padding: 0px 0px;
      font-size: 8px;
    }
    #four .gt_row {
      padding: 2px 3px;
      font-size: 6px;
    }
    #four .gt_col_heading {
      text-align: center !important;
    }
    ")
```



S5
================================================================================

```{r main2}
# Summary
## NOI
vr_points(x, by = "set", team_select = noi) %>% 
    bind_cols(vr_serve(x, by = "set", team_select = noi) %>% select(-set_number)) %>% 
    bind_cols(vr_reception(x, by = "set", team_select = noi) %>% select(-set_number)) %>% 
    bind_cols(vr_attack(x, by = "set", team_select = noi) %>% select(-set_number)) %>% 
    bind_cols(vr_freeball(x, by = "set", team_select = noi) %>% select(-set_number)) %>% 
    bind_cols(vr_block(x, by = "set", team_select = noi) %>% select(-set_number)) %>% 
    ### GT TABLE
    gt(id = "five") %>%
    tab_header(
      title = paste0(noi)) %>% 
    tab_spanner(
        label = "Punti",
        columns = Ser:Op.Er) %>% 
    tab_spanner(
        label = "Battuta",
        columns = Tot...7:Pos) %>% 
    tab_spanner(
        label = "Ricezione",
        columns = Tot...12:`(Exc%)`) %>% 
    tab_spanner(
        label = "Attacco",
        columns = Tot...17:`Pts%`) %>% 
    tab_spanner(
        label = "Freeball",
        columns = Tot...22:Err...23) %>%
    tab_spanner(
        label = "Muro",
        columns = Punto) %>%
    cols_label(
        set_number = html("Set"),
        Ser = html("Bat"),
        Blo...4 = html("Muto"),
        Tot...5 = html("<strong>Tot</strong>"),
        Tot...7 = html("<strong>Tot</strong>"),
        Err...8 = html("<strong>Err</strong>"),
        Pts...9 = html("Pts"),
        Tot...12 = html("<strong>Tot</strong>"),
        Err...13 = html("<strong>Err</strong>"),
        Tot...17 = html("<strong>Tot</strong>"),
        Err...18 = html("<strong>Err</strong>"),
        Blo...19 = html("Muto"),
        Pts...20 = html("Pts"),
        Tot...22 = html("<strong>Tot</strong>"),
        Err...23 = html("<strong>Err</strong>"),
        Punto = html("Pts")) %>% 
    cols_align(
    align = "center") %>% 
    tab_options(table.width = px(500)) %>% 
    opt_css(
    css = "
    #five .gt_col_heading {
      padding: 2px 3px;
      font-size: 8px;
    }
    #five .gt_column_spanner {
      padding: 0px 0px;
      font-size: 8px;
    }
    #five .gt_row {
      padding: 2px 3px;
      font-size: 6px;
    }
    #five .gt_col_heading {
      text-align: center !important;
    }
    ")

# Loro
vr_points(x, by = "set", team_select = loro) %>% 
    bind_cols(vr_serve(x, by = "set", team_select = loro) %>% select(-set_number)) %>% 
    bind_cols(vr_reception(x, by = "set", team_select = loro) %>% select(-set_number)) %>% 
    bind_cols(vr_attack(x, by = "set", team_select = loro) %>% select(-set_number)) %>% 
    bind_cols(vr_freeball(x, by = "set", team_select = loro) %>% select(-set_number)) %>% 
    bind_cols(vr_block(x, by = "set", team_select = loro) %>% select(-set_number)) %>% 
    ### GT TABLE
    gt(id = "five") %>%
    tab_header(
      title = paste0(loro)) %>% 
    tab_spanner(
        label = "Punti",
        columns = Ser:Op.Er) %>% 
    tab_spanner(
        label = "Battuta",
        columns = Tot...7:Pos) %>% 
    tab_spanner(
        label = "Ricezione",
        columns = Tot...12:`(Exc%)`) %>% 
    tab_spanner(
        label = "Attacco",
        columns = Tot...17:`Pts%`) %>% 
    tab_spanner(
        label = "Freeball",
        columns = Tot...22:Err...23) %>%
    tab_spanner(
        label = "Muro",
        columns = Punto) %>%
    cols_label(
        set_number = html("Set"),
        Ser = html("Bat"),
        Blo...4 = html("Muto"),
        Tot...5 = html("<strong>Tot</strong>"),
        Tot...7 = html("<strong>Tot</strong>"),
        Err...8 = html("<strong>Err</strong>"),
        Pts...9 = html("Pts"),
        Tot...12 = html("<strong>Tot</strong>"),
        Err...13 = html("<strong>Err</strong>"),
        Tot...17 = html("<strong>Tot</strong>"),
        Err...18 = html("<strong>Err</strong>"),
        Blo...19 = html("Muto"),
        Pts...20 = html("Pts"),
        Tot...22 = html("<strong>Tot</strong>"),
        Err...23 = html("<strong>Err</strong>"),
        Punto = html("Pts")) %>% 
    cols_align(
    align = "center") %>% 
    tab_options(table.width = px(500)) %>% 
    opt_css(
    css = "
    #five .gt_col_heading {
      padding: 2px 3px;
      font-size: 8px;
    }
    #five .gt_column_spanner {
      padding: 0px 0px;
      font-size: 8px;
    }
    #five .gt_row {
      padding: 2px 3px;
      font-size: 6px;
    }
    #five .gt_col_heading {
      text-align: center !important;
    }
    ")

```


S6
================================================================================


S7
================================================================================


